<AddMap>:
    MenuBox:
        orientation: 'vertical'
        SmallButton:
            text: 'Добавить картостиль'
#                on_press:
#                    root.manager.transition.direction = 'left'
#                    root.manager.current = 'optional_page'

        SmallButton:
            text: 'Список картостилей'
#                on_press:
#                    root.manager.transition.direction = 'left'
#                    root.manager.current = 'return_rockets'
